install bash script
kubeshop/kubtest pull request #310
Opened 2021-09-22 09:29 UTC by jasmingacic

This script will detect your OS and fetch the latest version - 0.5.21 unless you override by seting env var `KUBTEST_VERSION`

for example 
```sh
$ KUBTEST_VERSION=0.5.19 ./install.sh
Getting kubectl-kubtest plugin
Downloading kubtest from URL: https://github.com/kubeshop/kubtest/releases/download/v0.5.19/kubtest_0.5.19_Linux_x86_64.tar.gz
kubectl-kubtest installed in /usr/local/bin/kubectl-kubtest
```

or by simply running 
```sh
$ ./install.sh
Getting kubectl-kubtest plugin
Downloading kubtest from URL: https://github.com/kubeshop/kubtest/releases/download/v0.5.21/kubtest_0.5.21_Linux_x86_64.tar.gz
kubectl-kubtest installed in /usr/local/bin/kubectl-kubtest
```

Ideally we will do something like 
```sh
$ curl -sSLf https://get.kubtest.io | sudo sh
```

Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>

2021-09-22 11:09 UTC, exu submitted a review, later dismissed
Please update docs with install command

2021-09-22 14:02 UTC, nicufk requested changes
LGTM but waiting for official repo get.kubtest.io.

2021-09-23 21:45 UTC, hamzahsn approved these changes
LGTM!

2021-09-27 14:34 UTC, jasmingacic commented
Anyways with this PR install.sh will be moved to GH pages so the install command will be like:
```
$ curl -sSLf https://kubeshop.github.io/kubtest/install.sh | sudo bash
```

2021-09-27 14:37 UTC, jasmingacic commented
I also added option to test GH pages locally with docker-compose. 

```
$ cd doc
$ docker-compose up
```

http://localhost:8080

2021-09-27 14:51 UTC, nicufk approved these changes
👍

2021-09-27 14:56 UTC, merged

2021-09-27 19:17 UTC, jasmingacic commented on install.sh
> +KUBTEST_VERSION=${KUBTEST_VERSION:-"0.5.21"}
so right now our latest release is  `v0.5.26-beta001` `https://github.com/kubeshop/kubtest/releases/latest`  sine v0.5.26 is less than v0.5.26-beta001 :D